[package]
name = "rust-workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-says = "0.3.1"
rand = "0.8.5"

[workspace]
members = [ "blog", "concurrency", "functions", "hello-world", "smart-pointers", "tokio-workspace"]
